### ISSUE TITLE
Jellyfin port

### ISSUE THREAD

**Issue by Skyrisu** [bjoerns1983/Emby.Plugin.TelegramNotification#3]
I really like the addon but just switched from emby to jellyfin.
Would it be possible for you to port the plugin to jellyfin?
https://github.com/jellyfin/jellyfin-plugin-template

**Comment by bjoerns1983** [comment]
Give me a few days to have a look at it. 
Shouldnt be too hard.

**Comment by Skyrisu** [comment]
Great! Thank you :)

**Comment by anthonylavado** [comment]
From the Jellyfin core team here. Let us know if you need anything @bjoerns1983.

🙂

**Comment by bjoerns1983** [comment]
Okay was more work than i thought but the plugin is basicly useable, see here:
https://github.com/bjoerns1983/jellyfin-plugin-telegramnotification
Only thing which does not work atm is the Test Notifications Button. I always get an unknown Handler error. Must be a stupid error (my C# Knowledge is quite limited).
Maybe a dev @anthonylavado could have a look at it and maybe give me a PR. Than i would port back some minor updates from the current Emby Version of the Plugin an release a DLL.

**Comment by bjoerns1983** [comment]
Would be cool if someone could have a look at it.
Cant get the testbutton to work with Jellyfin, in Emby it works perfect, Jellyfin always throws a failure at the console when i push the button: Could not find handler for /emby/Notification/Telegram/Test

**Comment by anthonylavado** [comment]
Sorry, yeah - will do. Were you testing it against source or a release? I think we had just taken out those paths in master, (https://github.com/jellyfin/jellyfin/pull/1588) but we are going to add them back in before 10.4. They should still be present in release 10.3.7.

**Comment by bjoerns1983** [comment]
Yes that could definitely be the problem.
I am testing with the current portable Windows version, 10.3.7.
Normal Notifications work, only the Test Button makes problems.
Checked the ServerApiEntryPoint.cs and config.html multiple times, also compared it to the slack plugin but could not find anything obvious.
