### ISSUE TITLE
Feature Request: Add to Emby Plugin Catalog

### ISSUE THREAD

**Issue by mpearon** [bjoerns1983/Emby.Plugin.TelegramNotification#6]
@bjoerns1983 - Why is this plugin not in the Emby plugins catalog?  It appears to be functional.

**Comment by bjoerns1983** [comment]
It  is functional, i just dont like the way developers are treated there, so it is not on the catalog.

**Comment by mpearon** [comment]
Understood. I wish there was an easier way to surface these non-catalog extensions other than just crawling GitHub for "Emby" matches.
Great work on the extension! It's working beautifully in my environment.
